extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Death_Ma_Plane_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern Lights1 bob_dl_f3dlite_material_002_lights;
extern u8 bob_dl_SUPER_MARIO_64_E0BB9B61_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_E0BB9B61_0_2_all_pal_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Slide_Part_1_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Slide_Part_1_mesh_layer_1_vtx_0[2805];
extern Gfx bob_dl_Slide_Part_1_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Slide_Part_2_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Slide_Part_2_mesh_layer_1_vtx_0[2680];
extern Gfx bob_dl_Slide_Part_2_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Start_Plat_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Start_Plat_mesh_layer_1_vtx_0[72];
extern Gfx bob_dl_Start_Plat_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Death_Ma_Plane[];
extern Gfx mat_revert_bob_dl_Death_Ma_Plane[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_Slide_Part_1_mesh_layer_1[];
extern Gfx bob_dl_Slide_Part_2_mesh_layer_1[];
extern Gfx bob_dl_Start_Plat_mesh_layer_1[];
