extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_003_lights;
extern Lights1 jrb_dl_f3dlite_material_002_lights;
extern Lights1 jrb_dl_sm64_water_mat_lights;
extern Vtx jrb_dl_Bridge_1_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Bridge_1_mesh_layer_1_vtx_0[44];
extern Gfx jrb_dl_Bridge_1_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Bridge_1_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Bridge_1_001_mesh_layer_1_vtx_0[43];
extern Gfx jrb_dl_Bridge_1_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_0[17];
extern Gfx jrb_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Circle_001_mesh_layer_1_vtx_0[145];
extern Gfx jrb_dl_Circle_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_0[246];
extern Gfx jrb_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_001_mesh_layer_1_vtx_0[50];
extern Gfx jrb_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Starting_Plat_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Starting_Plat_mesh_layer_1_vtx_0[296];
extern Gfx jrb_dl_Starting_Plat_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Water_Box_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Water_Box_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Water_Box_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material_002[];
extern Gfx mat_jrb_dl_sm64_water_mat[];
extern Gfx jrb_dl_Bridge_1_mesh_layer_1[];
extern Gfx jrb_dl_Bridge_1_001_mesh_layer_1[];
extern Gfx jrb_dl_Circle_mesh_layer_1[];
extern Gfx jrb_dl_Circle_001_mesh_layer_1[];
extern Gfx jrb_dl_Cylinder_mesh_layer_1[];
extern Gfx jrb_dl_Cylinder_001_mesh_layer_1[];
extern Gfx jrb_dl_Starting_Plat_mesh_layer_1[];
extern Gfx jrb_dl_Water_Box_Mesh_mesh_layer_1[];
